version: '3.5'

services:

  gateway:
    container_name: quicktest-api-gateway
    image: quicktest/api-gateway
    build:
      context: .
      dockerfile: ./src/ApiGateway/Dockerfile

  products:
    container_name: quicktest-products
    image: quicktest/products
    build:
      context: .
      dockerfile: ./src/Product/Product.WebApi/Dockerfile.fast-jar

  customers:
    container_name: quicktest-customers
    image: quicktest/customers
    build:
      context: .
      dockerfile: ./src/Customer/Customer.WebApi/Dockerfile.fast-jar


  webapp:
    container_name: quicktest-webapp
    image: quicktest/webapp
    build:
      context: .
      dockerfile: ./src/webapp/Dockerfile